from fastapi.responses import HTMLResponse
from apps.design_tokens import WEB_CSS_VARS

MOBILE_HTML="""<!doctype html><html lang='vi'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>HMS QR Báo cáo gia công</title><style>
body{font-family:Segoe UI,sans-serif;background:#101923;color:#eef4fa;margin:0;overflow-wrap:anywhere}header{position:sticky;top:0;background:#182634;padding:12px}.wrap{max-width:680px;margin:auto;padding:14px}.card{background:#1b2b39;border:1px solid #304758;border-radius:10px;padding:14px;margin:12px 0}button,input,select,textarea{box-sizing:border-box;max-width:100%;font-size:16px;padding:11px;margin:4px;border-radius:8px;border:1px solid #4b6679;background:#243b4c;color:white}.attempt{background:#177e70}.done{background:#c27a17;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.label{color:#9eb3c2;font-size:12px}.value{font-weight:600}#history li{margin:7px 0}.mode{display:flex;flex-wrap:wrap}.qc-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.qc-actions button{margin:0}.history-kind{font-weight:700;color:#74d6c9}@media(max-width:430px){.grid,.qc-actions{grid-template-columns:1fr}.wrap{padding:8px}header{font-size:14px}}</style></head><body>
<header><div>NGƯỜI DÙNG: <b id='user'>Chưa chọn</b> <button onclick='changeUser()'>ĐỔI NGƯỜI DÙNG</button><div id='user-picker' hidden><select id='user-select'></select><input id='new-user' placeholder='Tên người dùng mới'><button onclick='selectUser()'>XÁC NHẬN USER</button></div></div><div>LOẠI GIA CÔNG: <b id='process'>Chưa chọn</b> <button onclick='changeProcess()'>ĐỔI LOẠI GIA CÔNG</button><div id='process-picker' hidden><select id='process-select'></select><button onclick='selectProcess()'>XÁC NHẬN LOẠI</button></div></div></header>
<main class='wrap'><div class='card'><h2>QUÉT QR</h2><input id='qr' placeholder='Nhập/paste mã QR'><button onclick='resolveScan()'>Tra cứu</button><small>Camera cần HTTPS/secure context; nhập mã là fallback phát triển.</small></div>
<div id='info' class='card' hidden><div class='grid' id='fields'></div></div>
<div id='actions' class='card' hidden><div class='mode'><button onclick="showMode('machining')">GIA CÔNG</button><button onclick="showMode('qc')">QC / GIAO HÀNG</button></div><section id='machining'><h3>BÁO CÁO GIA CÔNG</h3><div id='attempts'></div><button onclick='expandAttempts()'>+ THÊM LẦN</button><button class='done' onclick='submitCompleted()'>ĐÃ XONG</button><div><input id='qty' type='number' min='0.0001' placeholder='Số lượng'><input id='notes' placeholder='Ghi chú / nội dung báo cáo'></div></section><section id='qc' hidden><h3>QC / TRẠNG THÁI</h3><div class='qc-actions'><button onclick="openWorkflow('QC_CHECKED')">ĐÃ KIỂM TRA</button><button onclick="openWorkflow('SHORTAGE_REPORTED')">THIẾU HÀNG</button><button onclick="openWorkflow('QC_NG_RETURNED_TO_MACHINING')">NG TRẢ LẠI NC CHỜ XỬ LÝ</button><button onclick="openWorkflow('PACKED')">ĐÃ ĐÓNG GÓI</button><button onclick="openWorkflow('DELIVERED')">ĐÃ GIAO HÀNG</button><button onclick="openWorkflow('GENERAL_REPORT')">BÁO CÁO</button></div><div id='workflow-form' hidden><h4 id='workflow-title'></h4><input id='workflow-qty' type='number' min='0.0001' placeholder='Số lượng'><textarea id='workflow-notes' placeholder='NỘI DUNG BÁO CÁO / Ghi chú'></textarea><button onclick='sendWorkflow()'>GỬI BÁO CÁO</button></div></section></div>
<div class='card'><h3>LỊCH SỬ GẦN ĐÂY</h3><ul id='history'></ul></div></main><script>
let current=null,maxAttempt=3,workflowType=null;const api='/tracking';let userId=localStorage.getItem('hms-user-id'),processId=localStorage.getItem('hms-process-id');
async function changeUser(){const r=await fetch(api+'/api/v1/operators');if(!r.ok)return;const d=await r.json();document.querySelector('#user-select').innerHTML='<option value="">-- Chọn user --</option>'+d.items.map(x=>`<option value="${x.internal_id}">${x.display_name}</option>`).join('');document.querySelector('#user-picker').hidden=false}
async function selectUser(){const select=document.querySelector('#user-select');let u=select.value?{internal_id:select.value,display_name:select.options[select.selectedIndex].text}:null;const name=document.querySelector('#new-user').value.trim();if(!u&&name){const r=await fetch(api+'/api/v1/operators',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({display_name:name})});if(r.ok)u=await r.json()}if(!u)return;userId=u.internal_id;localStorage.setItem('hms-user-id',userId);localStorage.setItem('hms-user',u.display_name);document.querySelector('#user').textContent=u.display_name;document.querySelector('#user-picker').hidden=true}
async function changeProcess(){const r=await fetch(api+'/api/v1/machining-types');if(!r.ok)return;const d=await r.json();document.querySelector('#process-select').innerHTML='<option value="">-- Chọn loại --</option>'+d.items.map(x=>`<option value="${x.internal_id}">${x.display_name}</option>`).join('');document.querySelector('#process-picker').hidden=false}
async function selectProcess(){const select=document.querySelector('#process-select');if(!select.value)return;processId=select.value;const name=select.options[select.selectedIndex].text;localStorage.setItem('hms-process-id',processId);localStorage.setItem('hms-process',name);document.querySelector('#process').textContent=name;document.querySelector('#process-picker').hidden=true;if(userId)await fetch(api+'/api/v1/operators/'+userId+'/preference',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({machining_type_id:processId})})}
function restore(){document.querySelector('#user').textContent=localStorage.getItem('hms-user')||'Chưa chọn';document.querySelector('#process').textContent=localStorage.getItem('hms-process')||'Chưa chọn'}
async function resolveScan(){const q=document.querySelector('#qr').value;const r=await fetch(api+'/api/v1/scan?payload='+encodeURIComponent(q));if(!r.ok)return alert('Không tìm thấy QR');current=await r.json();await refreshProductCard();document.querySelector('#info').hidden=false;document.querySelector('#actions').hidden=false;document.querySelector('#qty').value=current.quantity;document.querySelector('#workflow-qty').value=current.quantity;if(userId&&!processId){const p=await fetch(api+'/api/v1/operators/'+userId+'/preference');if(p.ok){const d=await p.json();processId=d.machining_type_id}}if(processId){const a=await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/attempt-display?machining_type_id='+processId);if(a.ok)maxAttempt=(await a.json()).max_visible_attempt}renderAttempts();loadHistory()}
async function refreshProductCard(){if(!current)return;const s=await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/workflow-summary');if(s.ok)current.status=(await s.json()).current_status;const labels={part_name:'TÊN SẢN PHẨM',customer:'KHÁCH HÀNG',product_code:'MÃ SẢN PHẨM',tracking_code:'MÃ THEO DÕI',order_code:'MÃ ĐƠN / PO',delivery_date:'NGÀY GIAO HÀNG',quantity:'SỐ LƯỢNG',status:'TRẠNG THÁI'};document.querySelector('#fields').innerHTML=Object.entries(labels).map(([k,v])=>`<div><div class='label'>${v}</div><div class='value'>${current[k]||''}</div></div>`).join('')}
function showMode(mode){document.querySelector('#machining').hidden=mode!=='machining';document.querySelector('#qc').hidden=mode!=='qc'}
function openWorkflow(kind){workflowType=kind;const names={QC_CHECKED:'ĐÃ KIỂM TRA',SHORTAGE_REPORTED:'THIẾU HÀNG',QC_NG_RETURNED_TO_MACHINING:'NG TRẢ LẠI NC CHỜ XỬ LÝ',PACKED:'ĐÃ ĐÓNG GÓI',DELIVERED:'ĐÃ GIAO HÀNG',GENERAL_REPORT:'BÁO CÁO'};document.querySelector('#workflow-title').textContent=names[kind];document.querySelector('#workflow-qty').hidden=kind==='GENERAL_REPORT';document.querySelector('#workflow-form').hidden=false}
async function sendWorkflow(){if(!current||!userId||!workflowType)return alert('Cần chọn người dùng');const routes={QC_CHECKED:'qc-events',SHORTAGE_REPORTED:'qc-events',QC_NG_RETURNED_TO_MACHINING:'qc-events',PACKED:'packing-events',DELIVERED:'delivery-events',GENERAL_REPORT:'reports'};const body={request_id:crypto.randomUUID(),event_type:workflowType,quantity:workflowType==='GENERAL_REPORT'?null:document.querySelector('#workflow-qty').value,notes:document.querySelector('#workflow-notes').value,actor_user_id:userId,actor_display_name:document.querySelector('#user').textContent,machining_type_id:workflowType==='QC_NG_RETURNED_TO_MACHINING'?processId:null};const r=await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/'+routes[workflowType],{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const e=await r.json();return alert(e.error?.message||'Không thể ghi sự kiện')}document.querySelector('#workflow-form').hidden=true;await refreshProductCard();await loadHistory()}
function renderAttempts(){document.querySelector('#attempts').innerHTML=Array.from({length:maxAttempt},(_,i)=>`<button class='attempt' onclick='submitAttempt(${i+1})'>LẦN ${i+1}</button>`).join('')}
async function expandAttempts(){maxAttempt=Math.min(99,maxAttempt+3);if(current&&processId)await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/attempt-display/expand',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({machining_type_id:processId,new_max:maxAttempt,user_id:userId})});renderAttempts()}
async function submitAttempt(n){await submitReport('ATTEMPT',n)}async function submitCompleted(){await submitReport('PROCESS_COMPLETED',null)}
async function submitReport(kind,n){if(!current||!userId||!processId)return alert('Cần chọn người dùng và loại gia công');const body={request_id:crypto.randomUUID(),tracking_item_id:current.internal_id,machining_type_id:processId,kind,attempt_number:n,quantity:document.querySelector('#qty').value,notes:document.querySelector('#notes').value,actor_user_id:userId,actor_display_name:document.querySelector('#user').textContent};const r=await fetch(api+'/api/v1/process-reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.ok){alert('Đã ghi báo cáo');await loadHistory()}}
async function loadHistory(){if(!current)return;const r=await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/history');if(r.ok){const d=await r.json();const names={ATTEMPT:'Gia công',PROCESS_COMPLETED:'Đã xong',QC_CHECKED:'QC',SHORTAGE_REPORTED:'Thiếu hàng',QC_NG_RETURNED_TO_MACHINING:'NG / Rework',PACKED:'Đóng gói',DELIVERED:'Giao hàng',GENERAL_REPORT:'Báo cáo'};document.querySelector('#history').innerHTML=d.items.map(x=>`<li><span class='history-kind'>${names[x.event_type]||x.event_type}</span> — ${new Date(x.server_timestamp).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} — ${x.actor_display_name_snapshot}${x.quantity?' — '+x.quantity:''}${x.notes?' — '+x.notes:''}</li>`).join('')}}restore();</script></body></html>"""
def mobile_page():return HTMLResponse(MOBILE_HTML)
