from fastapi.responses import HTMLResponse

MOBILE_HTML="""<!doctype html><html lang='vi'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>HMS QR Báo cáo gia công</title><style>
body{font-family:Segoe UI,sans-serif;background:#101923;color:#eef4fa;margin:0}header{position:sticky;top:0;background:#182634;padding:12px}.wrap{max-width:680px;margin:auto;padding:14px}.card{background:#1b2b39;border:1px solid #304758;border-radius:10px;padding:14px;margin:12px 0}button,input,select{font-size:16px;padding:11px;margin:4px;border-radius:8px;border:1px solid #4b6679;background:#243b4c;color:white}.attempt{background:#177e70}.done{background:#c27a17;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.label{color:#9eb3c2;font-size:12px}.value{font-weight:600}#history li{margin:7px 0}</style></head><body>
<header><div>NGƯỜI DÙNG: <b id='user'>Chưa chọn</b> <button onclick='changeUser()'>ĐỔI NGƯỜI DÙNG</button></div><div>LOẠI GIA CÔNG: <b id='process'>Chưa chọn</b> <button onclick='changeProcess()'>ĐỔI LOẠI GIA CÔNG</button></div></header>
<main class='wrap'><div class='card'><h2>QUÉT QR</h2><input id='qr' placeholder='Nhập/paste mã QR'><button onclick='resolveScan()'>Tra cứu</button><small>Camera cần HTTPS/secure context; nhập mã là fallback phát triển.</small></div>
<div id='info' class='card' hidden><div class='grid' id='fields'></div></div>
<div id='actions' class='card' hidden><h3>BÁO CÁO GIA CÔNG</h3><div id='attempts'></div><button onclick='expandAttempts()'>+ THÊM LẦN</button><button class='done' onclick='submitCompleted()'>ĐÃ XONG</button><div><input id='qty' type='number' min='0.0001' placeholder='Số lượng'><input id='notes' placeholder='Ghi chú / nội dung báo cáo'></div></div>
<div class='card'><h3>LỊCH SỬ GẦN ĐÂY</h3><ul id='history'></ul></div></main><script>
let current=null,maxAttempt=3;const api='/tracking';let userId=localStorage.getItem('hms-user-id'),processId=localStorage.getItem('hms-process-id');
async function changeUser(){const n=prompt('Tên người dùng');if(!n)return;const r=await fetch(api+'/api/v1/operators',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({display_name:n})});if(r.ok){const u=await r.json();userId=u.internal_id;localStorage.setItem('hms-user-id',userId);localStorage.setItem('hms-user',u.display_name);document.querySelector('#user').textContent=u.display_name}}
async function changeProcess(){const r=await fetch(api+'/api/v1/machining-types');if(!r.ok)return;const d=await r.json();const name=prompt('Loại gia công: '+d.items.map(x=>x.display_name).join(', '));const p=d.items.find(x=>x.display_name.toUpperCase()===String(name).toUpperCase()||x.code===String(name).toUpperCase());if(p){processId=p.internal_id;localStorage.setItem('hms-process-id',processId);localStorage.setItem('hms-process',p.display_name);document.querySelector('#process').textContent=p.display_name;if(userId)await fetch(api+'/api/v1/operators/'+userId+'/preference',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({machining_type_id:processId})})}}
function restore(){document.querySelector('#user').textContent=localStorage.getItem('hms-user')||'Chưa chọn';document.querySelector('#process').textContent=localStorage.getItem('hms-process')||'Chưa chọn'}
async function resolveScan(){const q=document.querySelector('#qr').value;const r=await fetch(api+'/api/v1/scan?payload='+encodeURIComponent(q));if(!r.ok)return alert('Không tìm thấy QR');current=await r.json();const labels={part_name:'TÊN SẢN PHẨM',customer:'KHÁCH HÀNG',product_code:'MÃ SẢN PHẨM',tracking_code:'MÃ THEO DÕI',order_code:'MÃ ĐƠN / PO',delivery_date:'NGÀY GIAO HÀNG',quantity:'SỐ LƯỢNG',status:'TRẠNG THÁI'};document.querySelector('#fields').innerHTML=Object.entries(labels).map(([k,v])=>`<div><div class='label'>${v}</div><div class='value'>${current[k]||''}</div></div>`).join('');document.querySelector('#info').hidden=false;document.querySelector('#actions').hidden=false;document.querySelector('#qty').value=current.quantity;if(userId&&!processId){const p=await fetch(api+'/api/v1/operators/'+userId+'/preference');if(p.ok){const d=await p.json();processId=d.machining_type_id}}if(processId){const a=await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/attempt-display?machining_type_id='+processId);if(a.ok)maxAttempt=(await a.json()).max_visible_attempt}renderAttempts();loadHistory()}
function renderAttempts(){document.querySelector('#attempts').innerHTML=Array.from({length:maxAttempt},(_,i)=>`<button class='attempt' onclick='submitAttempt(${i+1})'>LẦN ${i+1}</button>`).join('')}
async function expandAttempts(){maxAttempt=Math.min(99,maxAttempt+3);if(current&&processId)await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/attempt-display/expand',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({machining_type_id:processId,new_max:maxAttempt,user_id:userId})});renderAttempts()}
async function submitAttempt(n){await submitReport('ATTEMPT',n)}async function submitCompleted(){await submitReport('PROCESS_COMPLETED',null)}
async function submitReport(kind,n){if(!current||!userId||!processId)return alert('Cần chọn người dùng và loại gia công');const body={request_id:crypto.randomUUID(),tracking_item_id:current.internal_id,machining_type_id:processId,kind,attempt_number:n,quantity:document.querySelector('#qty').value,notes:document.querySelector('#notes').value,actor_user_id:userId,actor_display_name:document.querySelector('#user').textContent};const r=await fetch(api+'/api/v1/process-reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.ok){alert('Đã ghi báo cáo');await loadHistory()}}
async function loadHistory(){if(!current)return;const r=await fetch(api+'/api/v1/tracking-items/'+current.internal_id+'/process-reports');if(r.ok){const d=await r.json();document.querySelector('#history').innerHTML=d.items.map(x=>`<li>${x.server_timestamp} — ${x.actor_display_name_snapshot} — ${x.kind==='ATTEMPT'?'Lần '+x.attempt_number:'Đã xong'} — ${x.quantity}</li>`).join('')}}restore();</script></body></html>"""
def mobile_page():return HTMLResponse(MOBILE_HTML)
